name: SnowTerritory
version: '${project.version}'
main: top.arctain.snowTerritory.Main
api-version: '1.21'
authors: [ Arctain ]
website: www.arctain.top
depend: [ MMOItems ]
softdepend: [ Vault, PlayerPoints, PlaceholderAPI ]
commands:
  snowterritory:
    description: SnowTerritory 主命令
    usage: /snowterritory <子命令>
    aliases: [sn]
    permission: mmoitemseditor.use
  snowterritoryenderstorage:
    description: EnderStorage 主命令
    usage: /snowterritoryenderstorage <子命令>
    aliases: [stes]
    permission: st.loot.use
permissions:
  mmoitemseditor.use:
    description: 允许使用 SnowTerritory 命令
    default: op
  mmoitemseditor.edit:
    description: 允许使用物品编辑功能
    default: op
  mmoitemseditor.reload:
    description: 允许重载插件配置
    default: op
  mmoitemseditor.itemid:
    description: 允许查看物品ID
    default: op
  mmoitemseditor.openforothers:
    description: 允许为其他玩家打开物品强化界面
    default: op
  st.loot.use:
    description: 使用战利品仓库
    default: true
  st.loot.auto:
    description: 自动拾取到战利品仓库
    default: op
  st.loot.admin:
    description: 管理战利品仓库
    default: op
  st.fish.use:
    description: 使用钓鱼功能
    default: true
  st.fish.weather:
    description: 召唤天气
    default: op
  st.fish.give:
    description: 给予玩家鱼类
    default: op
  st.armor.generate:
    description: 生成制式防具套装
    default: op
  st.vip.1:
    description: ST VIP 等级 1（展示名见 stvip/config.yml）
    default: false
  st.vip.2:
    description: ST VIP 等级 2（展示名见 stvip/config.yml）
    default: false
  st.vip.3:
    description: ST VIP 等级 3（展示名见 stvip/config.yml）
    default: false

